name: 'Upload files to a GitHub release'
description: 'Upload files to a GitHub release (cross-platform)'
author: 'Sven-Hendrik Haase'
branding:
  icon: archive
  color: orange
inputs:
  repo_token:
    description: 'GitHub token'
    required: true
  file:
    description: 'Local file to upload'
    required: true
  asset_name:
    description: 'Name of the asset'
    required: true
  tag:
    description: 'Tag to use as a release'
    required: true
  overwrite:
    description: 'Overwrite the release in case it already exists'
  file_glob:
    description: 'If true the file can be a glob pattern, asset_name is ignored if this is true'
  prerelease:
    description: 'Mark the release as a pre-release'
  body:
    description: 'Content of the release text'
outputs:
  browser_download_url:
    description: 'The publicly available URL of the asset.'
runs:
  using: 'node12'
  main: 'dist/index.js'
